<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ApplicationIcon>MateoFlowEditor.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="MateoFlowEditor.ico" />
  </ItemGroup>
</Project>